#!/bin/bash
cd client
cargo make build_release
mkdir -p ../server/public
cp -r pkg ../server/public/pkg
cd ..

cd server
cargo build --release
cd ..

mkdir -p target/release/public
cp -r server/public target/release/public